print ('Вид питомца')
type = input()
print ('Возраст питомца')
age = input()
print ('Кличка питомца')
nickname = input()
print ('Это', type, 'по кличке', '"'+nickname+'",', 'возраст:', age)

print()
print ('Первый этап развития человека')
stage_1 = input()
print ('Второй этап развития человека')
stage_2 = input()
print ('Третий этап развития человека')
stage_3 = input()
print ('Четвертый этап развития человека')
stage_4 = input()
print ('Пятый этап развития человека')
stage_5 = input()
print ('Шестой этап развития человека')
stage_6 = input()
print (stage_1, stage_2, stage_3, stage_4, stage_5, stage_6, sep='=')
